"""Add user_id in Booking

Revision ID: 5dab9e978a42
Revises: 58588e2d3056
Create Date: 2026-03-23 14:08:59.132194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dab9e978a42'
down_revision: Union[str, Sequence[str], None] = '58588e2d3056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('user_id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'user_id')
    # ### end Alembic commands ###
