"""change time to without timezone

Revision ID: 7cc50504b618
Revises: 54b2b5edac54
Create Date: 2026-03-22 19:20:14.997139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cc50504b618'
down_revision: Union[str, Sequence[str], None] = '54b2b5edac54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'room', ['id'])
    op.alter_column('schedule', 'start_time',
               existing_type=postgresql.TIME(timezone=True),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('schedule', 'end_time',
               existing_type=postgresql.TIME(timezone=True),
               type_=sa.Time(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'schedule', ['id'])
    op.create_unique_constraint(None, 'slot', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slot', type_='unique')
    op.drop_constraint(None, 'schedule', type_='unique')
    op.alter_column('schedule', 'end_time',
               existing_type=sa.Time(),
               type_=postgresql.TIME(timezone=True),
               existing_nullable=False)
    op.alter_column('schedule', 'start_time',
               existing_type=sa.Time(),
               type_=postgresql.TIME(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'room', type_='unique')
    # ### end Alembic commands ###
