"""Fix default time

Revision ID: b9d2eac36f13
Revises: 02fcc2ec58d7
Create Date: 2026-03-25 12:32:34.470381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d2eac36f13'
down_revision: Union[str, Sequence[str], None] = '02fcc2ec58d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_booking_slot_status', 'booking', ['slot_id', 'status'], unique=False)
    op.create_index('idx_slot_room_time', 'slot', ['room_id', 'start', 'end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_slot_room_time', table_name='slot')
    op.drop_index('idx_booking_slot_status', table_name='booking')
    # ### end Alembic commands ###
