"""Fix and add unique

Revision ID: e3f5c91aa6d1
Revises: 5dab9e978a42
Create Date: 2026-03-25 10:46:16.385185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f5c91aa6d1'
down_revision: Union[str, Sequence[str], None] = '5dab9e978a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_booking_slot_status'), table_name='booking')
    op.create_unique_constraint('unique_slot', 'booking', ['slot_id'])
    op.create_unique_constraint(None, 'slot', ['room_id', 'start', 'end'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slot', type_='unique')
    op.drop_constraint('unique_slot', 'booking', type_='unique')
    op.create_index(op.f('idx_booking_slot_status'), 'booking', ['slot_id', 'status'], unique=False)
    # ### end Alembic commands ###
